#!/usr/bin/env python

###############################################################################
#
# IBT: Isolated Build Tool
# Copyright (C) 2016, Richard Cook. All rights reserved.
#
# Simple wrappers around Docker etc. for fully isolated build environments
#
###############################################################################

import contextlib
import fcntl
import os
import shlex
import sys

from ibtimpl.context import *
from ibtimpl.docker_util import *
from ibtimpl.help_command import *
from ibtimpl.status_command import *

@contextlib.contextmanager
def try_acquire_lock(ctx):
    if not os.path.isdir(ctx.dot_dir):
        os.makedirs(ctx.dot_dir)

    with open(os.path.join(ctx.dot_dir, "lock"), "w") as f:
        try:
            fcntl.lockf(f, fcntl.LOCK_EX | fcntl.LOCK_NB)
            yield True
        except IOError:
            yield False

def resolve_local_path(ctx, path):
    return os.path.abspath(os.path.join(ctx.project_dir, path))

def run_command(ctx, argv):
    name = argv[0]
    command = get_commands().get(name, None)
    if command is None:
        raise RuntimeError("Unsupported command {}".format(name))

    args = command.parser.parse_args(argv[1 : ])
    command.run(ctx, args)

def find_config_file(dir):
    file_name = os.path.join(dir, "Ibtfile")
    if os.path.isfile(file_name):
        return file_name
    parent_dir = os.path.dirname(dir)
    return None if parent_dir == dir else find_config_file(parent_dir)

def main_inner(ctx, argv):
    if len(argv) < 2:
        HelpCommand().run(ctx, [])
        return

    command = argv[1]
    aliases = ctx.settings.get("aliases", None)
    if command in aliases:
        run_command(ctx, shlex.split(aliases[command]))
    else:
        run_command(ctx, argv[1 : ])

def main(dir, argv):
    if not docker_installed():
        print("Please install Docker")
        return

    config_path = find_config_file(dir)
    if config_path is None:
        print("No Ibtfile project configuration file could be found")
        return

    ctx = Context(dir, config_path)

    # Special-case the "status" command to report status even
    # if .ibt directory has not been created yet
    if not os.path.isdir(ctx.dot_dir) and argv[1 : ] == ["status"]:
        StatusCommand().run(ctx, [])
        return

    with try_acquire_lock(ctx) as result:
        if result:
            main_inner(ctx, argv)
        else:
            print("Another instance of ibt is already running")

if __name__ == "__main__":
    main(os.getcwd(), sys.argv)
