#!/usr/bin/env python

import hashlib
import os
import subprocess
import sys

def docker_image_exists(image_id):
  proc = subprocess.Popen(
    ["docker", "inspect", image_id],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE)
  proc.communicate()
  return proc.returncode == 0

def docker_image_build(image_id, project_dir):
  if not docker_image_exists(image_id):
    subprocess.check_call(["docker", "build", "-t", image_id, project_dir])

def docker_image_remove(image_id):
  if docker_image_exists(image_id):
    subprocess.check_call(["docker", "rmi", image_id])

class Context(object):
  def __init__(self, dir):
    ibt_file_name = self._find_ibt_file(dir)
    if ibt_file_name is None:
      raise RuntimeError("ibt command run outside project")

    self._project_id = hashlib.md5(ibt_file_name).hexdigest()
    self._image_id = "ibt-{}-image".format(self._project_id)
    self._container_id = "ibt-{}-container".format(self._project_id)
    self._project_dir = os.path.dirname(ibt_file_name)

  @property
  def project_id(self): return self._project_id

  @property
  def image_id(self): return self._image_id

  @property
  def container_id(self): return self._container_id

  @property
  def project_dir(self): return self._project_dir

  @staticmethod
  def _find_ibt_file(dir):
    file_name = os.path.join(dir, "Ibtfile")
    if os.path.isfile(file_name):
      return file_name
    parent_dir = os.path.dirname(dir)
    return None if parent_dir == dir else find_ibt_file(parent_dir)

def run_command(command):
  print(command)
  subprocess.check_call(command)

def do_up(ctx, args):
  if len(args) > 0:
    raise RuntimeError("up takes no arguments")

  docker_image_build(ctx.image_id, ctx.project_dir)

  dot_dir = os.path.join(ctx.project_dir, ".ibt")
  if not os.path.isdir(dot_dir):
    os.makedirs(dot_dir)

def do_destroy(ctx, args):
  if len(args) > 0:
    raise RuntimeError("destroy takes no arguments")

  docker_image_remove(ctx.image_id)

def do_run(dir, args):
  if len(args) == 0:
    raise RuntimeError("run takes one or more arguments")

  ibt_file_name = find_ibt_file(dir)
  if ibt_file_name is None:
    raise RuntimeError("ibt command run outside project")

  project_id = hashlib.md5(ibt_file_name).hexdigest()
  image_id = "ibt-{}-image".format(project_id)
  container_id = "ibt-{}-container".format(project_id)
  project_dir = os.path.dirname(ibt_file_name)

  rel_dir = os.path.relpath(dir, project_dir)
  with open(os.path.join(project_dir, ".ibt/docker-script.sh"), "wt") as f:
    f.write("#!/bin/sh\n")
    f.write("cd /project\n")
    f.write("cd {}\n".format(rel_dir))
    f.write(" ".join(args) + "\n")

  # Execute script inside container
  run_command([
    "docker",
    "run",
    "-v",
    "{}:{}".format(project_dir, "/project"),
    "--rm",
    image_id,
    "/bin/sh",
    "/project/.ibt/docker-script.sh"
  ])
    
def main(dir, args):
  args.pop(0)
  if len(args) < 1:
    raise RuntimeError("no ibt command specified")

  ctx = Context(dir)

  command = args.pop(0)
  if command == "up":
    do_up(ctx, args)
  elif command == "destroy":
    do_destroy(ctx, args)
  elif command == "run":
    do_run(dir, args)
  else:
    raise RuntimeError("Unsupported command {}".format(command))

if __name__ == "__main__":
  main(os.getcwd(), list(sys.argv))
